# Check security updates only
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'ryo-kozin'
    open-pull-requests-limit: 0 # Not to create PRs for version updates
    groups:
      patch-updates:
        applies-to: security-updates
        update-types:
          - 'patch'
        commit-message:
          prefix: 'patch'

      minor-updates:
        applies-to: security-updates
        update-types:
          - 'minor'
        commit-message:
          prefix: 'minor'

      major-updates:
        applies-to: security-updates
        update-types:
          - 'major'
        commit-message:
          prefix: 'major'
